### ISSUE TITLE
Configure SMTP for Mauro

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper-NHSD/nhsd-datadictionary-docker#18]
NHS England have provided the details for SMTP to be used in Mauro. They are:

- From address: datamodel.dictionaryservice1@nhs.net
- SMTP host: send.nhs.net
- SMTP port: 587
- SMTP username: datamodel.dictionaryservice1@nhs.net
- SMTP password: *talk to @pjmonks*

NHS England also provided this documentation page which may be helpful: https://support.nhs.net/knowledge-base/high-sending-smtp-solution/

These are configuration variables defined here: https://maurodatamapper.github.io/installing/configuring/mdm-core-config/

The "from" address is a Mauro API property that is configured at runtime:

1. Login as any administrator to MDM UI
2. Go to the "Configuration" page from your user menu
3. In the table of properties, look for `email.from.address` and edit that to the one above.

This will require the docker containers to be restarted to take affect. The docker logs starting up Tomcat should show either that SMTP was configured correctly, or show an error for why it failed.

To test that emails work:

1. Go to the main Mauro UI
2. Click "Log in"
3. Click on "Forgot password"
4. Enter your email address and click "Recover password"
5. This should trigger an email to be sent to you.

**Comment by mhocc** [comment]
On hold: it seems the credentials provided by NHS England are somehow wrong

**Comment by pjmonks** [comment]
This is now on hold indefinitely for the foreseeable future. NHS internally need to audit the Mauro solution before they can setup an email service correctly, which will take at least 6 weeks to approach. This is no longer in scope for System C to manage.
