### ISSUE TITLE
Move Postgres database shared volume to NVMe mount

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper-NHSD/nhsd-datadictionary-docker#19]
# Overview

NHS Data Solutions have provisioned the VMs for the hosting environments with a separate 1TB NVMe drive for the purpose of data storage and backups, primarily so that the Postgres database can grow to a large size and have fast IO on an SSD drive. However, I've been told that the TEST environment isn't using this mount, everything is running on the VM disk.

Swap the Postgresql database over to the NVMe mount for faster performance and increased storage.

Do this on the TRAINING environment first to confirm this works (depends on it being setup), then organise a time to do it on the TEST environment to not interfere with NHSE testing schedule.

# Additional Notes

Conversation from @jamesrwelch and @joe-crawford on Zulip:

> Peter Monks: @James Welch and @Mike Hewlett - I've been told by NHS Data Solutions that we have a NVMe drive provisioned for their VMs which we're not actually using, the Docker container for Postgres is using the shared volume on the host VM. How do we swap that to using a different mount?
> 
> James Welch: I'm not really sure, but our docker compose uses the standard postgres docker container, so it'll be their configuration rather than anything special
> 
> Joe Crawford: @Peter Monks Should just be a case of tweaking the volumes path under the postgres image in the docker-compose file: https://github.com/MauroDataMapper/mdm-docker/blob/main/docker-compose.yml
> 
> Joe Crawford: (postgres12:/var/lib/postgresql/data)
> 
> James Welch: :thumbs_up:
> 
> Peter Monks: Thanks, something I'll get @Mike Hewlett to look at
> 
> Joe Crawford: You'll probably want to repoint the paths under the mauro-data-mapper image too, especially the lucene one

Having looked at this I discovered that Docker stores its volumes under `/var/lib/docker/volumes` (the dir names below that are determined by the container and volume names), so if it is just volumes we could create a symlink for volumes but a better solution would be to configure where Docker keeps all its data via the `/etc/docker/daemon.json` which I'll try once the VMs become available.

**Comment by mhocc** [comment]
This is done and can be reviewed on the TRAINING server

**Comment by pjmonks** [comment]
@mhocc What is your opinion on changing the data volumes on the TEST server? Is it worth doing, given they are still doing active testing on the environment? Or at least explaining to NHS Data Solutions how to do it?

**Comment by pjmonks** [comment]
Going to put this on hold. The Test environment should also be updated to use the correct data mount, but we don't want to do this while NHS England are in the middle of testing.

**Comment by mhocc** [comment]
The test environment has now been updated - did this by simply copying the current `/var/lib/docker` contents to `/data/docker`, updated
the Docker configuration and restarted the service — seems to be working fine.
