### ISSUE TITLE
Define environment variables for TEST environment

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper-NHSD/nhsd-datadictionary-docker#4]
An `.env` file should defined for all the environment variables required for the NHS `TEST` environment VM - this is where the Docker images will be built and run from.

This should include:

- Ports to expose for the web applications
- Commits from the Git repository to fetch
- The required configuration options which must be overridden. See https://maurodatamapper.github.io/installing/configuring/mdm-core-config/#required-to-be-overridden
- Anything environment specific

The specific environment variable file can then be referenced in Docker commands like this:

```bash
docker compose --env-file .env.other ...
```

# Related

- NHSDigital/DataDictionaryPublication#317

**Comment by mhocc** [comment]
Noticed there is a problem with deployment of the orchestration UI - a recent change in the Docker configuration put it inside the ROOT - this will need fixing

**Comment by pjmonks** [comment]
@mhocc As I was working on finishing the TEST environment, I noticed that you have different bash scripts in place to sort out the environment variables. There are a few scripts in place now, I think we need to add some consistency. Things to consider:

1. There is an `up.sh` and a `develop-up.sh` script. Is it possible to have one `up.sh` and switch in different `.env` files per environment?
2. I don't use bash on my local machine (I use Powershell), so running the commands for `docker compose up` are a bit more cumbersome for me to test locally. Again, is there a way we can move the environment variables out to a separate file? I'm happy to run commands manually after that.
